#! /bin/sh

# Variáveis de Ambiente

export PATH="$HOME/.config/bspwm/bin:$PATH"

export XDG_CURRENT_DESKTOP='bspwm'
export XDG_SESSION_TYPE='x11'
export XDG_SESSION_DESKTOP='bspwm'
export _JAVA_AWT_NONREPARENTING=1

export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim

# Configuração de Monitor

bspc monitor -d I II III IV V VI VII

# Configuração do BSPWM

bspc config border_width        2
bspc config window_gap          7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Regras do BSPWM
# bspc rule -a Gimp desktop='^8' state=floating follow=on

# Autostart

# Variável exe
exe() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# Executa o xsettingsd
exe xsettingsd --config "${HOME}"/.config/bspwm/config/xsettingsd >/dev/null 2>&1

# Executa o picom
exe picom --config "${HOME}"/.config/bspwm/config/picom.conf

# sxhkd daemon
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/config/sxhkdrc &

xsetroot -cursor_name left_ptr


